export interface Car {
  slug: string;
  name: string;
  category: "supercar" | "sedan" | "suv";
  power: string;
  acceleration: string;
  engineVolume: string;
  fuelConsumption: string;
  maxSpeed: string;
  seats: number;
  drive: string;
  year: number;
  price: number;
  images: string[];
  powerEn: string;
  accelerationEn: string;
  engineVolumeEn: string;
  fuelConsumptionEn: string;
  maxSpeedEn: string;
  driveEn: string;
}

export const cars: Car[] = [
  // === СУПЕРКАРЫ (8) ===
  {
    slug: "ferrari-sf90",
    name: "Ferrari SF90",
    category: "supercar",
    power: "1000 л.с.",
    acceleration: "2.5 сек",
    engineVolume: "4.0 л",
    fuelConsumption: "8.6 л/100км",
    maxSpeed: "340 км/ч",
    seats: 2,
    drive: "AWD",
    year: 2024,
    price: 90000,
    images: ["/images/ferrari-sf90/1.webp", "/images/ferrari-sf90/2.webp", "/images/ferrari-sf90/3.webp"],
    powerEn: "1000 hp",
    accelerationEn: "2.5 sec",
    engineVolumeEn: "4.0 L",
    fuelConsumptionEn: "8.6 L/100km",
    maxSpeedEn: "340 km/h",
    driveEn: "AWD",
  },
  {
    slug: "porsche-911-turbo-s",
    name: "Porsche 911 Turbo S",
    category: "supercar",
    power: "650 л.с.",
    acceleration: "2.7 сек",
    engineVolume: "3.8 л",
    fuelConsumption: "12.3 л/100км",
    maxSpeed: "330 км/ч",
    seats: 4,
    drive: "AWD",
    year: 2024,
    price: 55000,
    images: ["/images/porsche-911-turbo-s/1.webp", "/images/porsche-911-turbo-s/2.webp", "/images/porsche-911-turbo-s/3.webp"],
    powerEn: "650 hp",
    accelerationEn: "2.7 sec",
    engineVolumeEn: "3.8 L",
    fuelConsumptionEn: "12.3 L/100km",
    maxSpeedEn: "330 km/h",
    driveEn: "AWD",
  },
  {
    slug: "lamborghini-huracan-sto",
    name: "Lamborghini Huracán STO",
    category: "supercar",
    power: "640 л.с.",
    acceleration: "3.0 сек",
    engineVolume: "5.2 л",
    fuelConsumption: "13.9 л/100км",
    maxSpeed: "310 км/ч",
    seats: 2,
    drive: "RWD",
    year: 2024,
    price: 75000,
    images: ["/images/lamborghini-huracan-sto/1.webp", "/images/lamborghini-huracan-sto/2.webp", "/images/lamborghini-huracan-sto/3.webp"],
    powerEn: "640 hp",
    accelerationEn: "3.0 sec",
    engineVolumeEn: "5.2 L",
    fuelConsumptionEn: "13.9 L/100km",
    maxSpeedEn: "310 km/h",
    driveEn: "RWD",
  },
  {
    slug: "bugatti-divo",
    name: "Bugatti Divo",
    category: "supercar",
    power: "1500 л.с.",
    acceleration: "2.4 сек",
    engineVolume: "8.0 л",
    fuelConsumption: "22.0 л/100км",
    maxSpeed: "380 км/ч",
    seats: 2,
    drive: "AWD",
    year: 2024,
    price: 90000,
    images: ["/images/bugatti-divo/1.webp", "/images/bugatti-divo/2.webp", "/images/bugatti-divo/3.webp"],
    powerEn: "1500 hp",
    accelerationEn: "2.4 sec",
    engineVolumeEn: "8.0 L",
    fuelConsumptionEn: "22.0 L/100km",
    maxSpeedEn: "380 km/h",
    driveEn: "AWD",
  },
  {
    slug: "mclaren-570s",
    name: "McLaren 570S",
    category: "supercar",
    power: "570 л.с.",
    acceleration: "3.2 сек",
    engineVolume: "3.8 л",
    fuelConsumption: "12.0 л/100км",
    maxSpeed: "328 км/ч",
    seats: 2,
    drive: "RWD",
    year: 2024,
    price: 65000,
    images: ["/images/mclaren-570s/1.webp", "/images/mclaren-570s/2.webp", "/images/mclaren-570s/3.webp"],
    powerEn: "570 hp",
    accelerationEn: "3.2 sec",
    engineVolumeEn: "3.8 L",
    fuelConsumptionEn: "12.0 L/100km",
    maxSpeedEn: "328 km/h",
    driveEn: "RWD",
  },
  {
    slug: "lamborghini-revuelto",
    name: "Lamborghini Revuelto",
    category: "supercar",
    power: "1015 л.с.",
    acceleration: "2.5 сек",
    engineVolume: "6.5 л",
    fuelConsumption: "15.0 л/100км",
    maxSpeed: "350 км/ч",
    seats: 2,
    drive: "AWD",
    year: 2024,
    price: 85000,
    images: ["/images/lamborghini-revuelto/1.webp", "/images/lamborghini-revuelto/2.webp", "/images/lamborghini-revuelto/3.webp"],
    powerEn: "1015 hp",
    accelerationEn: "2.5 sec",
    engineVolumeEn: "6.5 L",
    fuelConsumptionEn: "15.0 L/100km",
    maxSpeedEn: "350 km/h",
    driveEn: "AWD",
  },
  {
    slug: "ferrari-roma-spider",
    name: "Ferrari Roma Spider",
    category: "supercar",
    power: "620 л.с.",
    acceleration: "3.4 сек",
    engineVolume: "3.9 л",
    fuelConsumption: "11.0 л/100км",
    maxSpeed: "320 км/ч",
    seats: 2,
    drive: "RWD",
    year: 2024,
    price: 70000,
    images: ["/images/ferrari-roma-spider/1.webp", "/images/ferrari-roma-spider/2.webp", "/images/ferrari-roma-spider/3.webp"],
    powerEn: "620 hp",
    accelerationEn: "3.4 sec",
    engineVolumeEn: "3.9 L",
    fuelConsumptionEn: "11.0 L/100km",
    maxSpeedEn: "320 km/h",
    driveEn: "RWD",
  },
  {
    slug: "koenigsegg-jesko-mansory",
    name: "Koenigsegg Jesko Mansory",
    category: "supercar",
    power: "1600 л.с.",
    acceleration: "2.5 сек",
    engineVolume: "5.0 л",
    fuelConsumption: "18.0 л/100км",
    maxSpeed: "531 км/ч",
    seats: 2,
    drive: "RWD",
    year: 2024,
    price: 95000,
    images: ["/images/koenigsegg-jesko-mansory/1.webp", "/images/koenigsegg-jesko-mansory/2.webp", "/images/koenigsegg-jesko-mansory/3.webp"],
    powerEn: "1600 hp",
    accelerationEn: "2.5 sec",
    engineVolumeEn: "5.0 L",
    fuelConsumptionEn: "18.0 L/100km",
    maxSpeedEn: "531 km/h",
    driveEn: "RWD",
  },

  // === ЛЮКС-СЕДАНЫ (7) ===
  {
    slug: "bmw-m5-g90-mansory",
    name: "BMW M5 G90 Mansory",
    category: "sedan",
    power: "727 л.с.",
    acceleration: "3.3 сек",
    engineVolume: "4.4 л",
    fuelConsumption: "12.5 л/100км",
    maxSpeed: "305 км/ч",
    seats: 5,
    drive: "AWD",
    year: 2025,
    price: 45000,
    images: ["/images/bmw-m5-g90-mansory/1.webp", "/images/bmw-m5-g90-mansory/2.webp", "/images/bmw-m5-g90-mansory/3.webp"],
    powerEn: "727 hp",
    accelerationEn: "3.3 sec",
    engineVolumeEn: "4.4 L",
    fuelConsumptionEn: "12.5 L/100km",
    maxSpeedEn: "305 km/h",
    driveEn: "AWD",
  },
  {
    slug: "rolls-royce-ghost",
    name: "Rolls-Royce Ghost",
    category: "sedan",
    power: "571 л.с.",
    acceleration: "4.8 сек",
    engineVolume: "6.75 л",
    fuelConsumption: "15.0 л/100км",
    maxSpeed: "250 км/ч",
    seats: 5,
    drive: "AWD",
    year: 2024,
    price: 55000,
    images: ["/images/rolls-royce-ghost/1.webp", "/images/rolls-royce-ghost/2.webp", "/images/rolls-royce-ghost/3.webp"],
    powerEn: "571 hp",
    accelerationEn: "4.8 sec",
    engineVolumeEn: "6.75 L",
    fuelConsumptionEn: "15.0 L/100km",
    maxSpeedEn: "250 km/h",
    driveEn: "AWD",
  },
  {
    slug: "bentley-continental",
    name: "Bentley Continental",
    category: "sedan",
    power: "659 л.с.",
    acceleration: "3.5 сек",
    engineVolume: "6.0 л",
    fuelConsumption: "14.0 л/100км",
    maxSpeed: "335 км/ч",
    seats: 4,
    drive: "AWD",
    year: 2024,
    price: 48000,
    images: ["/images/bentley-continental/1.webp", "/images/bentley-continental/2.webp", "/images/bentley-continental/3.webp"],
    powerEn: "659 hp",
    accelerationEn: "3.5 sec",
    engineVolumeEn: "6.0 L",
    fuelConsumptionEn: "14.0 L/100km",
    maxSpeedEn: "335 km/h",
    driveEn: "AWD",
  },
  {
    slug: "mercedes-s63-brabus-930",
    name: "Mercedes-Benz S63 Brabus 930",
    category: "sedan",
    power: "930 л.с.",
    acceleration: "3.3 сек",
    engineVolume: "4.0 л",
    fuelConsumption: "13.5 л/100км",
    maxSpeed: "330 км/ч",
    seats: 5,
    drive: "AWD",
    year: 2024,
    price: 60000,
    images: ["/images/mercedes-s63-brabus-930/1.webp", "/images/mercedes-s63-brabus-930/2.webp", "/images/mercedes-s63-brabus-930/3.webp"],
    powerEn: "930 hp",
    accelerationEn: "3.3 sec",
    engineVolumeEn: "4.0 L",
    fuelConsumptionEn: "13.5 L/100km",
    maxSpeedEn: "330 km/h",
    driveEn: "AWD",
  },
  {
    slug: "mercedes-e63",
    name: "Mercedes-Benz E63",
    category: "sedan",
    power: "800 л.с.",
    acceleration: "3.0 сек",
    engineVolume: "4.0 л",
    fuelConsumption: "12.8 л/100км",
    maxSpeed: "320 км/ч",
    seats: 5,
    drive: "AWD",
    year: 2024,
    price: 42000,
    images: ["/images/mercedes-e63/1.webp", "/images/mercedes-e63/2.webp", "/images/mercedes-e63/3.webp"],
    powerEn: "800 hp",
    accelerationEn: "3.0 sec",
    engineVolumeEn: "4.0 L",
    fuelConsumptionEn: "12.8 L/100km",
    maxSpeedEn: "320 km/h",
    driveEn: "AWD",
  },
  {
    slug: "rolls-royce-spectre",
    name: "Rolls-Royce Spectre",
    category: "sedan",
    power: "585 л.с.",
    acceleration: "4.5 сек",
    engineVolume: "Электро",
    fuelConsumption: "0 л/100км",
    maxSpeed: "250 км/ч",
    seats: 4,
    drive: "AWD",
    year: 2024,
    price: 58000,
    images: ["/images/rolls-royce-spectre/1.webp", "/images/rolls-royce-spectre/2.webp", "/images/rolls-royce-spectre/3.webp"],
    powerEn: "585 hp",
    accelerationEn: "4.5 sec",
    engineVolumeEn: "Electric",
    fuelConsumptionEn: "0 L/100km",
    maxSpeedEn: "250 km/h",
    driveEn: "AWD",
  },
  {
    slug: "bmw-7-series",
    name: "BMW 7 Series",
    category: "sedan",
    power: "750 л.с.",
    acceleration: "3.5 сек",
    engineVolume: "4.4 л",
    fuelConsumption: "13.0 л/100км",
    maxSpeed: "290 км/ч",
    seats: 5,
    drive: "AWD",
    year: 2024,
    price: 40000,
    images: ["/images/bmw-7-series/1.webp", "/images/bmw-7-series/2.webp", "/images/bmw-7-series/3.webp"],
    powerEn: "750 hp",
    accelerationEn: "3.5 sec",
    engineVolumeEn: "4.4 L",
    fuelConsumptionEn: "13.0 L/100km",
    maxSpeedEn: "290 km/h",
    driveEn: "AWD",
  },

  // === ВНЕДОРОЖНИКИ (5) ===
  {
    slug: "lamborghini-urus",
    name: "Lamborghini Urus",
    category: "suv",
    power: "666 л.с.",
    acceleration: "3.3 сек",
    engineVolume: "4.0 л",
    fuelConsumption: "14.0 л/100км",
    maxSpeed: "306 км/ч",
    seats: 5,
    drive: "AWD",
    year: 2024,
    price: 65000,
    images: ["/images/lamborghini-urus/1.webp", "/images/lamborghini-urus/2.webp", "/images/lamborghini-urus/3.webp"],
    powerEn: "666 hp",
    accelerationEn: "3.3 sec",
    engineVolumeEn: "4.0 L",
    fuelConsumptionEn: "14.0 L/100km",
    maxSpeedEn: "306 km/h",
    driveEn: "AWD",
  },
  {
    slug: "rolls-royce-cullinan",
    name: "Rolls-Royce Cullinan",
    category: "suv",
    power: "632 л.с.",
    acceleration: "4.9 сек",
    engineVolume: "6.75 л",
    fuelConsumption: "15.5 л/100км",
    maxSpeed: "260 км/ч",
    seats: 5,
    drive: "AWD",
    year: 2024,
    price: 70000,
    images: ["/images/rolls-royce-cullinan/1.webp", "/images/rolls-royce-cullinan/2.webp", "/images/rolls-royce-cullinan/3.webp"],
    powerEn: "632 hp",
    accelerationEn: "4.9 sec",
    engineVolumeEn: "6.75 L",
    fuelConsumptionEn: "15.5 L/100km",
    maxSpeedEn: "260 km/h",
    driveEn: "AWD",
  },
  {
    slug: "mercedes-g63",
    name: "Mercedes-Benz G63",
    category: "suv",
    power: "900 л.с.",
    acceleration: "3.2 сек",
    engineVolume: "4.5 л",
    fuelConsumption: "17.0 л/100км",
    maxSpeed: "280 км/ч",
    seats: 5,
    drive: "AWD",
    year: 2024,
    price: 60000,
    images: ["/images/mercedes-g63/1.webp", "/images/mercedes-g63/2.webp", "/images/mercedes-g63/3.webp"],
    powerEn: "900 hp",
    accelerationEn: "3.2 sec",
    engineVolumeEn: "4.5 L",
    fuelConsumptionEn: "17.0 L/100km",
    maxSpeedEn: "280 km/h",
    driveEn: "AWD",
  },
  {
    slug: "range-rover",
    name: "Range Rover",
    category: "suv",
    power: "530 л.с.",
    acceleration: "4.6 сек",
    engineVolume: "4.4 л",
    fuelConsumption: "13.0 л/100км",
    maxSpeed: "261 км/ч",
    seats: 5,
    drive: "AWD",
    year: 2024,
    price: 40000,
    images: ["/images/range-rover/1.webp", "/images/range-rover/2.webp", "/images/range-rover/3.webp"],
    powerEn: "530 hp",
    accelerationEn: "4.6 sec",
    engineVolumeEn: "4.4 L",
    fuelConsumptionEn: "13.0 L/100km",
    maxSpeedEn: "261 km/h",
    driveEn: "AWD",
  },
  {
    slug: "bentley-bentayga",
    name: "Bentley Bentayga",
    category: "suv",
    power: "635 л.с.",
    acceleration: "3.9 сек",
    engineVolume: "6.0 л",
    fuelConsumption: "16.0 л/100км",
    maxSpeed: "306 км/ч",
    seats: 5,
    drive: "AWD",
    year: 2024,
    price: 50000,
    images: ["/images/bentley-bentayga/1.webp", "/images/bentley-bentayga/2.webp", "/images/bentley-bentayga/3.webp"],
    powerEn: "635 hp",
    accelerationEn: "3.9 sec",
    engineVolumeEn: "6.0 L",
    fuelConsumptionEn: "16.0 L/100km",
    maxSpeedEn: "306 km/h",
    driveEn: "AWD",
  },
];
